"""
Module 1 — Phishing / Malicious URL Classifier
Closes official requirement 4c / 6a (missing entirely in v1.0).

Model: XGBoost over 12 lexical + host-based URL features.
Training data: seed CSV generated by seed_data.py (PhishTank-style patterns + benign Tranco-1M style URLs).
Accuracy: ~95%+ on balanced splits per published literature.
Inference: sub-100ms — runs inline when a URL is pasted into the report form.

Human-in-the-loop: risk_score is returned to the officer/app; nothing is auto-blocked.
"""

import re
import math
import os
import urllib.parse
from urllib.parse import urlparse
from pathlib import Path

import pandas as pd
import xgboost as xgb
import joblib

# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------
MODEL_PATH = Path(__file__).parent.parent / "models" / "phishing_xgb.joblib"

SUSPICIOUS_TLDS = {
    ".xyz", ".top", ".click", ".tk", ".gq", ".work", ".loan",
    ".buzz", ".icu", ".live", ".fun", ".monster", ".cyou",
}

RISK_KEYWORDS = re.compile(
    r"(login|verify|update|secure|account|bank|confirm|reset|password|"
    r"signin|checkout|support|unlock|suspended|validate|billing)",
    re.IGNORECASE,
)


# ---------------------------------------------------------------------------
# Feature extraction
# ---------------------------------------------------------------------------
def extract_features(url: str) -> dict:
    """
    Extract 12 lexical + host-based features from a URL string.
    No DNS calls — runs entirely offline for speed and privacy.
    """
    if "://" not in url:
        url = f"http://{url}"
    parsed = urlparse(url)
    host = parsed.netloc.lower().split(":")[0]  # strip port
    path = parsed.path
    full = url.lower()

    def shannon_entropy(s: str) -> float:
        if not s:
            return 0.0
        probs = [s.count(c) / len(s) for c in set(s)]
        return -sum(p * math.log2(p) for p in probs)

    # Homoglyph / punycode check (e.g., xn-- encoded IDN phishing)
    has_punycode = int("xn--" in host)

    # Count query parameters (many params can indicate redirect abuse)
    num_params = len(urllib.parse.parse_qs(parsed.query))

    return {
        "url_length": len(url),
        "host_length": len(host),
        "num_dots": host.count("."),
        "num_hyphens": host.count("-"),
        "has_at_symbol": int("@" in url),
        "has_ip_host": int(bool(re.match(r"^\d{1,3}(\.\d{1,3}){3}$", host))),
        "suspicious_tld": int(any(host.endswith(t) for t in SUSPICIOUS_TLDS)),
        "entropy": round(shannon_entropy(host), 4),
        "num_subdirs": path.count("/"),
        "has_https": int(parsed.scheme == "https"),
        "digit_ratio": round(sum(c.isdigit() for c in host) / max(len(host), 1), 4),
        "has_risk_keyword": int(bool(RISK_KEYWORDS.search(full))),
        "has_punycode": has_punycode,
        "num_query_params": num_params,
    }


FEATURE_COLS = list(extract_features("http://example.com").keys())


# ---------------------------------------------------------------------------
# Training
# ---------------------------------------------------------------------------
def train(
    csv_path: str = "data/phishing_urls.csv",
    out_path: str = str(MODEL_PATH),
) -> xgb.XGBClassifier:
    """
    Train XGBoost on labelled URL data.
    CSV must have columns: url, label  (0=benign, 1=phishing)
    Public datasets: PhishTank, OpenPhish, Tranco top-1M for benign.
    """
    df = pd.read_csv(csv_path)
    feats = pd.DataFrame([extract_features(u) for u in df["url"]])
    model = xgb.XGBClassifier(
        n_estimators=200,
        max_depth=6,
        learning_rate=0.1,
        subsample=0.8,
        colsample_bytree=0.8,
        eval_metric="logloss",
        use_label_encoder=False,
        random_state=42,
    )
    model.fit(feats, df["label"])
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    joblib.dump(model, out_path)
    acc = model.score(feats, df["label"])
    print(f"[phishing] Saved -> {out_path}  |  train accuracy = {acc:.3f}")
    return model


# ---------------------------------------------------------------------------
# Inference
# ---------------------------------------------------------------------------
def load_model(path: str = str(MODEL_PATH)) -> xgb.XGBClassifier:
    return joblib.load(path)


def score_url(model: xgb.XGBClassifier, url: str) -> dict:
    """
    Returns a risk score (0–100) with top contributing feature signals.
    flag_for_review=True routes to the police AI-risk queue (threshold ≥ 60).
    """
    feats = extract_features(url)
    df = pd.DataFrame([feats])
    proba = float(model.predict_proba(df)[0][1])  # P(phishing)

    # Top 3 features by absolute value (explainability — §3.7 guardrail)
    top_signals = sorted(feats.items(), key=lambda kv: -abs(kv[1]))[:3]

    return {
        "url": url,
        "risk_score": round(proba * 100, 1),
        "confidence": round(max(proba, 1 - proba), 3),
        "top_signals": [k for k, _ in top_signals],
        "flag_for_review": proba >= 0.6,
        "note": "Signal for a human reviewer — not an auto-block verdict.",
    }


if __name__ == "__main__":
    import sys
    if len(sys.argv) > 1 and sys.argv[1] == "train":
        train()
